package ui.login;

import data.CommunityAdmin;
import data.CommunityDirectory;
import data.Doctor;
import data.EmergencyServices;
import data.EmergencyServicesDirectory;
import data.Fireman;
import data.MNCDirectory;
import data.MNCReperesentative;
import data.Police;
import data.Resident;
import data.UsersDirectory;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import ui.screens.admin.AdminDashboard;
import ui.screens.commadmin.CommAdminDashboard;
import ui.screens.commadmin.CommAdminPostbox;
import ui.screens.doctor.DoctorDashboard;
import ui.screens.fireman.FireManDashboard;
import ui.screens.ForgotPassword;
import ui.screens.NeedHelp;
import ui.screens.police.PoliceDashboard;
import ui.screens.RegisterResident;
import ui.screens.mnc.MNCAdminPostbox;
import ui.screens.mnc.MNCDashboard;
import ui.screens.resident.ResidentDashboard;
import utils.FileUtils;
import utils.ImagePanel;
import utils.SplashScreen;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author prath
 */
public class LoginPanel extends javax.swing.JFrame {

    private String usernameAdmin = "admin";
    private String passwordAdmin = "admin123";
    private String mncAdmin = "mnc";
    private String mncPassword = "mnc123";
    private ArrayList<Resident> residents = FileUtils.readResidents();
    private ArrayList<CommunityAdmin> commadmin = FileUtils.readCommunityAdmins();
    private ArrayList<Fireman> firemen = FileUtils.readFiremen();
    private ArrayList<Police> police = FileUtils.readPolice();
    private ArrayList<Doctor> doctor = FileUtils.readDoctors();
    private ArrayList<MNCReperesentative> mncr = FileUtils.readMNCR();
    private UsersDirectory personDirectory = new UsersDirectory();
    private CommunityDirectory communityDirectory = new CommunityDirectory();
    private EmergencyServicesDirectory es = new EmergencyServicesDirectory();
    private MNCDirectory mncd = new MNCDirectory();

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        initImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        adminUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adminPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        loginButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Knowbourhood");

        adminUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        loginButton.setBackground(new java.awt.Color(194, 129, 71));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Enter");
        loginButton.setBorder(null);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login");

        loginButton2.setBackground(new java.awt.Color(194, 129, 71));
        loginButton2.setForeground(new java.awt.Color(255, 255, 255));
        loginButton2.setText("Forgot Password");
        loginButton2.setBorder(null);
        loginButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("New User? Click here to register.");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Need Help?  Knowbourhoodians are there for you.");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1167, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(loginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(adminUsername)
                                            .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        login();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButton2ActionPerformed
        super.dispose();
        ForgotPassword fp = new ForgotPassword();
        fp.setVisible(true);
    }//GEN-LAST:event_loginButton2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        super.dispose();
        RegisterResident rr = new RegisterResident();
        rr.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        super.dispose();
        NeedHelp nh = new NeedHelp();
        nh.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    @SuppressWarnings("unchecked")
    private void initImage() {
        Font font = jLabel5.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jLabel5.setFont(font.deriveFont(attributes));
        jLabel6.setFont(font.deriveFont(attributes));
        ImagePanel jPanel1 = new ImagePanel("src/assets/globe.jpg");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }

    private void login() {
        String username = adminUsername.getText();
        String password = String.valueOf(adminPassword.getPassword());

        for (Resident r : residents) {
            if (r.getUsername().equals(username)) {
                if (r.getPassword().equals(password)) {
                    super.dispose();
                    ResidentDashboard rd = new ResidentDashboard(r);
                    rd.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Welcome!");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Username or Password!!!");
                }
                return;
            }
        }

        for (CommunityAdmin c : commadmin) {
            if (c.getUsername().equals(username)) {
                if (c.getPassword().equals(password)) {
                    super.dispose();
                    CommAdminDashboard rd = new CommAdminDashboard(c);
                    rd.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Welcome!");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Username or Password!!!");
                }
                return;
            }
        }

        for (Police p : police) {
            if (p.getUsername().equals(username)) {
                if (p.getPassword().equals(password)) {
                    super.dispose();
                    PoliceDashboard rd = new PoliceDashboard(p);
                    rd.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Welcome Officer!");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Username or Password!!!");
                }
                return;
            }
        }

        for (Fireman f : firemen) {
            if (f.getUsername().equals(username)) {
                if (f.getPassword().equals(password)) {
                    super.dispose();
                    FireManDashboard rd = new FireManDashboard(f);
                    rd.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Welcome Officer!");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Username or Password!!!");
                }
                return;
            }
        }

        for (Doctor d : doctor) {
            if (d.getUsername().equals(username)) {
                if (d.getPassword().equals(password)) {
                    super.dispose();
                    DoctorDashboard rd = new DoctorDashboard(d);
                    rd.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Welcome Doctor!");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Username or Password!!!");
                }
                return;
            }
        }
        
        for (MNCReperesentative m : mncr) {
            if (m.getUsername().equals(username)) {
                if (m.getPassword().equals(password)) {
                    super.dispose();
                    MNCAdminPostbox mad = new MNCAdminPostbox();
                    mad.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Welcome!");
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong Username or Password!!!");
                }
                return;
            }
        }

        if (usernameAdmin.equals(username) && passwordAdmin.equals(password)) {
            super.dispose();
            AdminDashboard ad = new AdminDashboard();
            ad.setVisible(true);
            JOptionPane.showMessageDialog(this, "Welcome!");
            return;
        } else if (mncAdmin.equals(username) && mncPassword.equals(password)) {
            super.dispose();
            MNCDashboard ad = new MNCDashboard();
            ad.setVisible(true);
            JOptionPane.showMessageDialog(this, "Welcome!");
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Wrong Username or Password!!!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SplashScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JTextField adminUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton loginButton2;
    // End of variables declaration//GEN-END:variables
}
